[package]
name = "calculator"
version = "0.1.0"
authors = ["Pablo Silva <pablodiegoss@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "calculator"
crate-type = ["cdylib"]

[dependencies]
